version: "2"

linters:
  enable:
    # Bug detection
    - errcheck
    - govet
    - staticcheck
    - ineffassign
    - unused
    - bodyclose
    - nilerr
    - noctx
    - durationcheck
    - errchkjson
    - makezero
    # Style (library-appropriate)
    - asciicheck
    - bidichk
    - copyloopvar
    - errname
    - misspell
    - nakedret
    - nolintlint
    - unconvert
    - usestdlibvars
    - wastedassign
    - whitespace
    # Testing
    - testifylint
    - thelper

run:
  exclude-dirs:
    - tmp
    - node_modules
    - dist
