package cli

import (
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/spf13/cobra"

	"github.com/iota-uz/applets/internal/applet/pkgjson"
	"github.com/iota-uz/applets/internal/config"
	"github.com/iota-uz/applets/internal/devsetup"
)

type sdkPackageMeta struct {
	Name string `json:"name"`
}

const pnpmfileTemplate = `// Auto-generated by "applet sdk link". This file is gitignored.
// It hooks into pnpm resolution to redirect @iota-uz/sdk to a local checkout.
function readPackage(pkg) {
  const target = 'link:%s';
  if (pkg.dependencies && pkg.dependencies['@iota-uz/sdk']) {
    pkg.dependencies['@iota-uz/sdk'] = target;
  }
  if (pkg.devDependencies && pkg.devDependencies['@iota-uz/sdk']) {
    pkg.devDependencies['@iota-uz/sdk'] = target;
  }
  return pkg;
}
module.exports = { hooks: { readPackage } };
`

func NewSDKCommand() *cobra.Command {
	var sdkRootFlag string
	cmd := &cobra.Command{
		Use:   "sdk",
		Short: "Manage local @iota-uz/sdk linking",
		Long: `Manage local @iota-uz/sdk link workflows for fast iteration.

These commands write gitignored .pnpmfile.cjs hooks that redirect @iota-uz/sdk
to a local checkout. The hooks survive pnpm install and never modify package.json.`,
	}
	cmd.PersistentFlags().StringVar(&sdkRootFlag, "sdk-root", "", "Path to local applets repository (canonical @iota-uz/sdk source)")

	linkCmd := &cobra.Command{
		Use:     "link",
		Short:   "Link local @iota-uz/sdk into applet consumers",
		Example: "  applet sdk link --sdk-root ../../applets",
		RunE: func(c *cobra.Command, _ []string) error {
			return runSDKLink(c, sdkRootFlag)
		},
	}
	unlinkCmd := &cobra.Command{
		Use:     "unlink",
		Short:   "Unlink local @iota-uz/sdk and restore pinned versions",
		Example: "  applet sdk unlink",
		RunE: func(c *cobra.Command, _ []string) error {
			return runSDKUnlink(c, sdkRootFlag)
		},
	}

	cmd.AddCommand(linkCmd, unlinkCmd)
	return cmd
}

func runSDKLink(cmd *cobra.Command, sdkRootFlag string) error {
	root, cfg, err := config.LoadFromCWD()
	if err != nil {
		return err
	}
	ctx := cmd.Context()

	sdkRoot, err := resolveSDKRoot(root, sdkRootFlag)
	if err != nil {
		return err
	}
	cmd.Printf("Ensuring SDK dependencies are installed in %s\n", sdkRoot)
	if err := devsetup.RunCommand(ctx, sdkRoot, "pnpm", "install", "--frozen-lockfile"); err != nil {
		return fmt.Errorf("install SDK dependencies in %s: %w", sdkRoot, err)
	}
	targets, err := discoverSDKTargets(root, cfg)
	if err != nil {
		return err
	}
	if len(targets) == 0 {
		return errors.New("no package.json files with @iota-uz/sdk dependency found")
	}

	for _, dir := range targets {
		cmd.Printf("Writing .pnpmfile.cjs in %s → %s\n", dir, sdkRoot)
		if err := writePnpmfileHook(dir, sdkRoot); err != nil {
			return fmt.Errorf("write .pnpmfile.cjs in %s: %w", dir, err)
		}
		cmd.Printf("Reinstalling dependencies in %s\n", dir)
		if err := devsetup.RunCommand(ctx, root, "pnpm", "-C", dir, "install"); err != nil {
			return fmt.Errorf("pnpm install in %s: %w", dir, err)
		}
	}

	localEnv := map[string]string{
		"APPLET_SDK_ROOT":      sdkRoot,
		"APPLET_SDK_LINK_MODE": "pnpmfile",
		"IOTA_SDK_DIST":        filepath.Join(sdkRoot, "dist"),
	}
	if err := writeLocalEnvFile(root, localEnv); err != nil {
		return err
	}
	cmd.Printf("Saved local overrides to %s\n", localEnvPath(root))
	cmd.Println("Linked. The .pnpmfile.cjs hooks are gitignored and survive pnpm install.")
	return nil
}

func runSDKUnlink(cmd *cobra.Command, _ string) error {
	root, cfg, err := config.LoadFromCWD()
	if err != nil {
		return err
	}
	ctx := cmd.Context()

	targets, err := discoverSDKTargets(root, cfg)
	if err != nil {
		return err
	}
	if len(targets) == 0 {
		cmd.Println("No @iota-uz/sdk consumers found. Nothing to unlink.")
		return nil
	}

	for _, dir := range targets {
		hookPath := filepath.Join(dir, ".pnpmfile.cjs")
		if err := os.Remove(hookPath); err != nil && !os.IsNotExist(err) {
			cmd.Printf("Warning: could not remove %s: %v\n", hookPath, err)
		} else if err == nil {
			cmd.Printf("Removed .pnpmfile.cjs from %s\n", dir)
		}
		cmd.Printf("Reinstalling pinned dependencies in %s\n", dir)
		if err := devsetup.RunCommand(ctx, root, "pnpm", "-C", dir, "install", "--frozen-lockfile"); err != nil {
			return fmt.Errorf("restore deps in %s: %w", dir, err)
		}
	}

	if err := os.Remove(localEnvPath(root)); err != nil && !os.IsNotExist(err) {
		return fmt.Errorf("remove %s: %w", localEnvPath(root), err)
	}
	cmd.Println("Local SDK link removed.")
	return nil
}

func writePnpmfileHook(dir, sdkRoot string) error {
	content := fmt.Sprintf(pnpmfileTemplate, sdkRoot)
	return os.WriteFile(filepath.Join(dir, ".pnpmfile.cjs"), []byte(content), 0o644)
}

func discoverSDKTargets(root string, cfg *config.ProjectConfig) ([]string, error) {
	seen := make(map[string]struct{})
	addIfConsumer := func(dir string) error {
		deps, err := pkgjson.Read(dir)
		if err != nil {
			if os.IsNotExist(err) {
				return nil
			}
			return nil
		}
		if pkgjson.SDKSpec(deps) == "" {
			return nil
		}
		absDir, err := filepath.Abs(dir)
		if err != nil {
			return err
		}
		seen[absDir] = struct{}{}
		return nil
	}

	if err := addIfConsumer(root); err != nil {
		return nil, err
	}
	for _, name := range cfg.AppletNames() {
		webDir := filepath.Join(root, cfg.Applets[name].Web)
		if err := addIfConsumer(webDir); err != nil {
			return nil, err
		}
	}

	dirs := make([]string, 0, len(seen))
	for dir := range seen {
		dirs = append(dirs, dir)
	}
	sort.Strings(dirs)
	return dirs, nil
}

func resolveSDKRootFromLocalOrFlags(root, sdkRootFlag string) (string, error) {
	if strings.TrimSpace(sdkRootFlag) != "" {
		return resolveSDKRoot(root, sdkRootFlag)
	}
	localEnv, err := readLocalEnvFile(root)
	if err == nil {
		if savedRoot := strings.TrimSpace(localEnv["APPLET_SDK_ROOT"]); savedRoot != "" {
			return resolveSDKRoot(root, savedRoot)
		}
	}
	return resolveSDKRoot(root, "")
}

func resolveSDKRoot(root, sdkRootFlag string) (string, error) {
	var candidates []string
	if strings.TrimSpace(sdkRootFlag) != "" {
		candidates = append(candidates, sdkRootFlag)
	} else if fromEnv := strings.TrimSpace(os.Getenv("APPLET_SDK_ROOT")); fromEnv != "" {
		candidates = append(candidates, fromEnv)
	} else {
		candidates = append(candidates,
			root,
			filepath.Join(root, "..", "applets"),
			filepath.Join(root, "..", "..", "applets"),
			filepath.Join(root, "..", "..", "..", "applets"),
		)
	}

	for _, candidate := range candidates {
		absCandidate, err := filepath.Abs(candidate)
		if err != nil {
			continue
		}
		name, err := readPackageName(absCandidate)
		if err != nil {
			continue
		}
		if name == "@iota-uz/sdk" {
			return absCandidate, nil
		}
	}

	return "", errors.New("could not find canonical @iota-uz/sdk source; pass --sdk-root or set APPLET_SDK_ROOT")
}

func readPackageName(dir string) (string, error) {
	p := filepath.Join(dir, "package.json")
	data, err := os.ReadFile(p)
	if err != nil {
		return "", err
	}
	var meta sdkPackageMeta
	if err := json.Unmarshal(data, &meta); err != nil {
		return "", err
	}
	return strings.TrimSpace(meta.Name), nil
}
